"""server_default en columnas de estado

Revision ID: 601414c9c4e7
Revises: 6fddad5eecab
Create Date: 2026-09-18 23:20:10.997764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601414c9c4e7'
down_revision: Union[str, Sequence[str], None] = '6fddad5eecab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumno', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', 'baja', name='estado_alumno'),
               server_default=sa.text("'activo'"),
               existing_nullable=False)
    op.alter_column('cargo', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'pagado', 'parcial', 'pago_en_revision', name='estado_cargo'),
               server_default=sa.text("'pendiente'"),
               existing_nullable=False)
    op.alter_column('evento_institucional', 'tipo',
               existing_type=postgresql.ENUM('gala', 'otro', name='tipo_evento'),
               server_default=sa.text("'otro'"),
               existing_nullable=False)
    op.alter_column('grupo_clase', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', name='estado_grupo'),
               server_default=sa.text("'activo'"),
               existing_nullable=False)
    op.alter_column('inscripcion', 'estado',
               existing_type=postgresql.ENUM('activa', 'baja', 'suspendida', name='estado_inscripcion'),
               server_default=sa.text("'activa'"),
               existing_nullable=False)
    op.alter_column('liquidacion', 'estado',
               existing_type=postgresql.ENUM('generada', 'aprobada', 'pagada', name='estado_liquidacion'),
               server_default=sa.text("'generada'"),
               existing_nullable=False)
    op.alter_column('lista_espera', 'estado',
               existing_type=postgresql.ENUM('esperando', 'convocado', 'descartado', name='estado_lista_espera'),
               server_default=sa.text("'esperando'"),
               existing_nullable=False)
    op.alter_column('usuario', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', name='estado_usuario'),
               server_default=sa.text("'activo'"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', name='estado_usuario'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lista_espera', 'estado',
               existing_type=postgresql.ENUM('esperando', 'convocado', 'descartado', name='estado_lista_espera'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('liquidacion', 'estado',
               existing_type=postgresql.ENUM('generada', 'aprobada', 'pagada', name='estado_liquidacion'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inscripcion', 'estado',
               existing_type=postgresql.ENUM('activa', 'baja', 'suspendida', name='estado_inscripcion'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('grupo_clase', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', name='estado_grupo'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evento_institucional', 'tipo',
               existing_type=postgresql.ENUM('gala', 'otro', name='tipo_evento'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cargo', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'pagado', 'parcial', 'pago_en_revision', name='estado_cargo'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alumno', 'estado',
               existing_type=postgresql.ENUM('activo', 'inactivo', 'baja', name='estado_alumno'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
