"""schema inicial completo

Revision ID: 6fddad5eecab
Revises: 
Create Date: 2026-09-18 22:50:28.540553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fddad5eecab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Todas las PK son UUID con server_default=gen_random_uuid(), que
    # requiere la extensión pgcrypto — se activa acá, antes de crear
    # cualquier tabla (autogenerate no la detecta sola, hay que agregarla
    # a mano).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto_cobro',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_recurrente', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('monto_sugerido', sa.Numeric(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('criterio_evaluacion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tiene_profesorado', sa.Boolean(), nullable=False),
    sa.Column('arancel_base', sa.Numeric(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('grupo_familiar',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('padre_tutor',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('parentesco', sa.Enum('madre', 'padre', 'tutor', 'abuelo_abuela', 'otro', name='parentesco'), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'secretaria', 'profesor', 'alumno', 'tutor', name='rol_usuario'), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_usuario'), nullable=False),
    sa.Column('fecha_alta', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alumno',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('datos_medicos', sa.String(), nullable=True),
    sa.Column('telefono_contacto', sa.String(), nullable=True),
    sa.Column('autorizacion_imagen', sa.Boolean(), nullable=False),
    sa.Column('apto_fisico_presentado', sa.Boolean(), nullable=False),
    sa.Column('apto_fisico_fecha', sa.Date(), nullable=True),
    sa.Column('grupo_familiar_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', 'baja', name='estado_alumno'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_familiar_id'], ['grupo_familiar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('comprobante',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_anulacion', sa.Date(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('emitido_por', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['emitido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre_institucion', sa.String(), server_default=sa.text("'Escuela de Danzas CREAR'"), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono_contacto', sa.String(), nullable=True),
    sa.Column('email_contacto', sa.String(), nullable=True),
    sa.Column('cbu_alias_transferencia', sa.String(), nullable=True),
    sa.Column('leyenda_comprobante', sa.Text(), nullable=True),
    sa.Column('arancel_cuota_base', sa.Numeric(), server_default=sa.text('40000'), nullable=False),
    sa.Column('arancel_matricula_base', sa.Numeric(), server_default=sa.text('20000'), nullable=False),
    sa.Column('dia_vencimiento_cuota', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('porcentaje_recargo_mora', sa.Numeric(), server_default=sa.text('5'), nullable=False),
    sa.Column('porcentaje_descuento_familiar', sa.Numeric(), server_default=sa.text('10'), nullable=False),
    sa.Column('umbral_asistencia_alerta', sa.Numeric(), server_default=sa.text('75'), nullable=False),
    sa.Column('plazo_dias_apto_fisico', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('cupo_maximo_default', sa.Integer(), server_default=sa.text('25'), nullable=False),
    sa.Column('habilitar_mercadopago', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mp_public_key', sa.String(), nullable=True),
    sa.Column('mp_access_token', sa.String(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_institucional',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('gala', 'otro', name='tipo_evento'), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('hora_evento', sa.Time(), nullable=True),
    sa.Column('lugar', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_limite_pago', sa.Date(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('mapa_asientos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_clase',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('disciplina_id', sa.UUID(), nullable=False),
    sa.Column('es_profesorado', sa.Boolean(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('nombre_display', sa.String(), nullable=True),
    sa.Column('profesora_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_grupo'), nullable=False),
    sa.Column('arancel_mensual', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidacion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.Column('estado', sa.Enum('generada', 'aprobada', 'pagada', name='estado_liquidacion'), nullable=False),
    sa.Column('aprobada_por', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aprobada_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_auditoria',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('entidad_afectada', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sueldo_usuario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno_tutor',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('padre_tutor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['padre_tutor_id'], ['padre_tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grupo_clase_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_clase_horario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grupo_clase_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', name='dia_semana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('grupo_clase_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'baja', 'suspendida', name='estado_inscripcion'), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_espera',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('grupo_clase_id', sa.UUID(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.Enum('esperando', 'convocado', 'descartado', name='estado_lista_espera'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vestuario_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evento_institucional_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['evento_institucional_id'], ['evento_institucional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inscripcion_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripcion.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('concepto_cobro_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('monto_original', sa.Numeric(), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('recargo_aplicado', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('monto_final', sa.Numeric(), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', 'parcial', 'pago_en_revision', name='estado_cargo'), nullable=False),
    sa.Column('generado_por', sa.UUID(), nullable=True),
    sa.Column('grupo_clase_id', sa.UUID(), nullable=True),
    sa.Column('evento_institucional_id', sa.UUID(), nullable=True),
    sa.Column('fila', sa.String(), nullable=True),
    sa.Column('columna', sa.Integer(), nullable=True),
    sa.Column('vestuario_evento_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['concepto_cobro_id'], ['concepto_cobro.id'], ),
    sa.ForeignKeyConstraint(['evento_institucional_id'], ['evento_institucional.id'], ),
    sa.ForeignKeyConstraint(['generado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ),
    sa.ForeignKeyConstraint(['vestuario_evento_id'], ['vestuario_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('cargo_butaca_activa_unica', 'cargo', ['evento_institucional_id', 'fila', 'columna'], unique=True, postgresql_where=sa.text("estado IN ('pendiente', 'pago_en_revision', 'pagado')"))
    op.create_table('examen_criterio',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('examen_id', sa.UUID(), nullable=False),
    sa.Column('criterio_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterio_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones_leidas',
    sa.Column('notificacion_id', sa.UUID(), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificaciones.id'], ),
    sa.PrimaryKeyConstraint('notificacion_id', 'alumno_id')
    )
    op.create_table('calificacion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('examen_criterio_id', sa.UUID(), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('profesora_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Numeric(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_carga', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('corregida_por', sa.UUID(), nullable=True),
    sa.Column('fecha_correccion', sa.Date(), nullable=True),
    sa.CheckConstraint('nota >= 1 AND nota <= 10', name='calificacion_nota_rango'),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['corregida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['examen_criterio_id'], ['examen_criterio.id'], ),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cargo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'mercadopago', name='metodo_pago'), nullable=False),
    sa.Column('referencia_externa', sa.Text(), nullable=True),
    sa.Column('comprobante_id', sa.UUID(), nullable=True),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('calificacion')
    op.drop_table('notificaciones_leidas')
    op.drop_table('examen_criterio')
    op.drop_index('cargo_butaca_activa_unica', table_name='cargo', postgresql_where=sa.text("estado IN ('pendiente', 'pago_en_revision', 'pagado')"))
    op.drop_table('cargo')
    op.drop_table('asistencia')
    op.drop_table('vestuario_evento')
    op.drop_table('notificaciones')
    op.drop_table('lista_espera')
    op.drop_table('inscripcion')
    op.drop_table('grupo_clase_horario')
    op.drop_table('examen')
    op.drop_table('alumno_tutor')
    op.drop_table('sueldo_usuario')
    op.drop_table('registro_auditoria')
    op.drop_table('liquidacion')
    op.drop_table('grupo_clase')
    op.drop_table('evento_institucional')
    op.drop_table('configuracion_sistema')
    op.drop_table('comprobante')
    op.drop_table('alumno')
    op.drop_table('usuario')
    op.drop_table('padre_tutor')
    op.drop_table('grupo_familiar')
    op.drop_table('disciplina')
    op.drop_table('criterio_evaluacion')
    op.drop_table('concepto_cobro')
    # ### end Alembic commands ###
