"""auditoria mecanica contra schema_original_supabase

Revision ID: d382b7b81528
Revises: f5d72c8e5bf9
Create Date: 2026-09-19 00:06:30.143677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd382b7b81528'
down_revision: Union[str, Sequence[str], None] = 'f5d72c8e5bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargo', 'descuento_aplicado',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cargo', 'recargo_aplicado',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('configuracion_sistema', sa.Column('kapso_api_key', sa.String(), nullable=True))
    op.alter_column('configuracion_sistema', 'direccion',
               existing_type=sa.TEXT(),
               server_default=sa.text("'Barrio Observatorio, Córdoba'"),
               existing_nullable=True)
    op.alter_column('configuracion_sistema', 'leyenda_comprobante',
               existing_type=sa.TEXT(),
               server_default=sa.text("'Comprobante administrativo interno - Escuela de Danzas CREAR'"),
               existing_nullable=True)
    op.alter_column('disciplina', 'tiene_profesorado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('grupo_clase', 'es_profesorado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('grupo_clase', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('registro_auditoria', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('clock_timestamp()'),
               existing_nullable=False)
    # ### end Alembic commands ###

    # ### agregado a mano — autogenerate no detectó esto ###

    # Precisión numérica exacta (autogenerate considera "40000" y "40000.00"
    # equivalentes y no marca diff, pero Postgres SÍ guarda la escala del
    # literal en columnas numeric sin precisión declarada — confirmado
    # a mano que el default en vivo seguía siendo "40000", no "40000.00").
    op.alter_column('configuracion_sistema', 'arancel_cuota_base',
               existing_type=sa.NUMERIC(), server_default=sa.text('40000.00'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'arancel_matricula_base',
               existing_type=sa.NUMERIC(), server_default=sa.text('20000.00'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'porcentaje_recargo_mora',
               existing_type=sa.NUMERIC(), server_default=sa.text('5.00'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'porcentaje_descuento_familiar',
               existing_type=sa.NUMERIC(), server_default=sa.text('10.00'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'umbral_asistencia_alerta',
               existing_type=sa.NUMERIC(), server_default=sa.text('75.00'), existing_nullable=False)
    op.alter_column('cargo', 'descuento_aplicado',
               existing_type=sa.NUMERIC(), server_default=sa.text('0.00'), existing_nullable=True)
    op.alter_column('cargo', 'recargo_aplicado',
               existing_type=sa.NUMERIC(), server_default=sa.text('0.00'), existing_nullable=True)

    # CHECK constraints — autogenerate no los detecta en Postgres, hay que
    # crearlos a mano siempre (no es un caso puntual de esta migración).
    op.create_check_constraint('alumno_fecha_nacimiento_check', 'alumno', 'fecha_nacimiento < CURRENT_DATE')
    op.create_check_constraint('configuracion_sistema_dia_vencimiento_check', 'configuracion_sistema',
                                'dia_vencimiento_cuota >= 1 AND dia_vencimiento_cuota <= 28')
    op.create_check_constraint('configuracion_sistema_recargo_check', 'configuracion_sistema',
                                'porcentaje_recargo_mora >= 0')
    op.create_check_constraint('configuracion_sistema_descuento_check', 'configuracion_sistema',
                                'porcentaje_descuento_familiar >= 0')
    op.create_check_constraint('configuracion_sistema_umbral_check', 'configuracion_sistema',
                                'umbral_asistencia_alerta >= 0 AND umbral_asistencia_alerta <= 100')
    op.create_check_constraint('asistencia_fecha_check', 'asistencia', 'fecha <= CURRENT_DATE')
    op.create_check_constraint('comprobante_numero_check', 'comprobante', 'numero > 0')
    op.create_check_constraint('cargo_monto_original_check', 'cargo', 'monto_original > 0')
    op.create_check_constraint('cargo_descuento_aplicado_check', 'cargo',
                                'descuento_aplicado IS NULL OR descuento_aplicado >= 0')
    op.create_check_constraint('cargo_recargo_aplicado_check', 'cargo',
                                'recargo_aplicado IS NULL OR recargo_aplicado >= 0')
    op.create_check_constraint('cargo_monto_final_check', 'cargo', 'monto_final >= 0')
    op.create_check_constraint('pago_fecha_pago_check', 'pago', 'fecha_pago <= CURRENT_DATE')
    op.create_check_constraint('pago_monto_check', 'pago', 'monto > 0')
    op.create_check_constraint('sueldo_usuario_monto_check', 'sueldo_usuario', 'monto > 0')
    op.create_check_constraint('liquidacion_monto_check', 'liquidacion', 'monto >= 0')

    # calificacion_nota_rango ya existía (desde la migración inicial) pero
    # con precisión "1"/"10" en vez de "1.00"/"10.00" del original — se
    # recrea con la precisión exacta.
    op.drop_constraint('calificacion_nota_rango', 'calificacion', type_='check')
    op.create_check_constraint('calificacion_nota_rango', 'calificacion', 'nota >= 1.00 AND nota <= 10.00')


def downgrade() -> None:
    """Downgrade schema."""
    # Reverso de lo agregado a mano, en orden inverso al upgrade.
    op.drop_constraint('calificacion_nota_rango', 'calificacion', type_='check')
    op.create_check_constraint('calificacion_nota_rango', 'calificacion', 'nota >= 1 AND nota <= 10')

    op.drop_constraint('liquidacion_monto_check', 'liquidacion', type_='check')
    op.drop_constraint('sueldo_usuario_monto_check', 'sueldo_usuario', type_='check')
    op.drop_constraint('pago_monto_check', 'pago', type_='check')
    op.drop_constraint('pago_fecha_pago_check', 'pago', type_='check')
    op.drop_constraint('cargo_monto_final_check', 'cargo', type_='check')
    op.drop_constraint('cargo_recargo_aplicado_check', 'cargo', type_='check')
    op.drop_constraint('cargo_descuento_aplicado_check', 'cargo', type_='check')
    op.drop_constraint('cargo_monto_original_check', 'cargo', type_='check')
    op.drop_constraint('comprobante_numero_check', 'comprobante', type_='check')
    op.drop_constraint('asistencia_fecha_check', 'asistencia', type_='check')
    op.drop_constraint('configuracion_sistema_umbral_check', 'configuracion_sistema', type_='check')
    op.drop_constraint('configuracion_sistema_descuento_check', 'configuracion_sistema', type_='check')
    op.drop_constraint('configuracion_sistema_recargo_check', 'configuracion_sistema', type_='check')
    op.drop_constraint('configuracion_sistema_dia_vencimiento_check', 'configuracion_sistema', type_='check')
    op.drop_constraint('alumno_fecha_nacimiento_check', 'alumno', type_='check')

    op.alter_column('cargo', 'recargo_aplicado',
               existing_type=sa.NUMERIC(), server_default=sa.text('0'), existing_nullable=True)
    op.alter_column('cargo', 'descuento_aplicado',
               existing_type=sa.NUMERIC(), server_default=sa.text('0'), existing_nullable=True)
    op.alter_column('configuracion_sistema', 'umbral_asistencia_alerta',
               existing_type=sa.NUMERIC(), server_default=sa.text('75'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'porcentaje_descuento_familiar',
               existing_type=sa.NUMERIC(), server_default=sa.text('10'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'porcentaje_recargo_mora',
               existing_type=sa.NUMERIC(), server_default=sa.text('5'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'arancel_matricula_base',
               existing_type=sa.NUMERIC(), server_default=sa.text('20000'), existing_nullable=False)
    op.alter_column('configuracion_sistema', 'arancel_cuota_base',
               existing_type=sa.NUMERIC(), server_default=sa.text('40000'), existing_nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registro_auditoria', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('grupo_clase', 'nivel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grupo_clase', 'es_profesorado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('disciplina', 'tiene_profesorado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('configuracion_sistema', 'leyenda_comprobante',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('configuracion_sistema', 'direccion',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('configuracion_sistema', 'kapso_api_key')
    op.alter_column('cargo', 'recargo_aplicado',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cargo', 'descuento_aplicado',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
