"""actualizado_en usa clock_timestamp

Revision ID: f5d72c8e5bf9
Revises: 9d20aa42ef98
Create Date: 2026-09-18 23:43:06.271638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5d72c8e5bf9'
down_revision: Union[str, Sequence[str], None] = '9d20aa42ef98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configuracion_sistema', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('clock_timestamp()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configuracion_sistema', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
